spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=riteshkumar
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
